// 方便书写和检测
export const SET_ACCOUNTOBJ = 'SET_ACCOUNTOBJ'

export const REMOVE_ACCOUNTOBJ = 'REMOVE_ACCOUNTOBJ'

export const SET_SESSIONIDOBJ = 'SET_SESSIONIDOBJ'

export const REMOVE_SESSIONIDOBJ = 'REMOVE_SESSIONIDOBJ'

export const SET_LANGSTE = 'SET_LANGSTE'

export const SET_ACCESSTOKEN = 'SET_ACCESSTOKEN'

export const SET_LOADING = 'SET_LOADING' 

export const SET_COMEFROM = 'SET_COMEFROM'

export const REMOVE_COMEFROM = 'REMOVE_COMEFROM'
